apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    enable-controller-attach-detach: "false"
discovery:
  bootstrapToken:
    apiServerEndpoint: ${API_ENDPOINT_INTERNAL}
    token: ${TOKEN}
    caCertHashes:
    - ${CA_CERT_HASH}